/**
 * The draft endpoints, typed.
 *
 * Every write takes the version the caller last read and sends it as `If-Match`. That is not
 * optional politeness: the wizard autosaves while the seller types and the same draft can be open
 * in two tabs, so without it the later write silently wins and earlier answers disappear with
 * nothing to explain where they went.
 */

import { request } from "./client";
import type {
  AnswerSaveResult,
  CategoryAttributes,
  Draft,
  DraftDetails,
  FieldOptions,
  SubmitResult,
  WizardStage,
} from "./types";

const DRAFTS = "/api/v1/me/advertisements";

export function categoryAttributes(
  categorySlug: string,
  signal?: AbortSignal,
): Promise<CategoryAttributes> {
  return request(`/api/v1/categories/${categorySlug}/attributes`, { signal });
}

/**
 * Options for one dataset-backed field.
 *
 * @param parent the answer to the field named by `data_source_parent` — a make, for a model.
 *   Omitted for a flat dataset.
 */
export function fieldOptions(
  categorySlug: string,
  fieldKey: string,
  parent?: string | null,
  signal?: AbortSignal,
): Promise<FieldOptions> {
  return request(`/api/v1/categories/${categorySlug}/attributes/${fieldKey}/options`, {
    query: { parent },
    signal,
  });
}

/**
 * Starts a draft.
 *
 * The idempotency key is generated by the caller and reused across retries, so a double-tap on a
 * slow connection returns the first draft instead of creating a second one the seller cannot tell
 * apart from it.
 */
export function createDraft(category: string, idempotencyKey: string): Promise<Draft> {
  return request(DRAFTS, {
    method: "POST",
    body: { category },
    idempotencyKey,
  });
}

export function getDraft(reference: string, signal?: AbortSignal): Promise<Draft> {
  return request(`${DRAFTS}/${reference}`, { signal });
}

export function saveAnswers(
  reference: string,
  answers: Record<string, unknown>,
  ifMatch: number,
): Promise<AnswerSaveResult> {
  return request(`${DRAFTS}/${reference}/answers`, {
    method: "PATCH",
    body: { answers },
    ifMatch,
  });
}

/** Clears one answer. Distinct from saving an empty value, which the server cannot tell apart. */
export function clearAnswer(
  reference: string,
  fieldKey: string,
  ifMatch: number,
): Promise<AnswerSaveResult> {
  return request(`${DRAFTS}/${reference}/answers/${fieldKey}`, {
    method: "DELETE",
    ifMatch,
  });
}

export function skipAnswer(reference: string, fieldKey: string): Promise<Draft> {
  return request(`${DRAFTS}/${reference}/answers/${fieldKey}/skip`, { method: "POST" });
}

export function saveDetails(
  reference: string,
  details: DraftDetails,
  ifMatch: number,
): Promise<Draft> {
  return request(`${DRAFTS}/${reference}/details`, {
    method: "PATCH",
    body: details,
    ifMatch,
  });
}

/** Records progress, so an abandoned draft resumes where the seller left off. */
export function reachStage(reference: string, stage: WizardStage): Promise<Draft> {
  return request(`${DRAFTS}/${reference}/stage`, {
    method: "POST",
    body: { stage },
  });
}

export function submitDraft(reference: string, ifMatch: number): Promise<SubmitResult> {
  return request(`${DRAFTS}/${reference}/submit`, { method: "POST", ifMatch });
}
